"""Constants used across the facial recognition scripts."""

from __future__ import annotations

from pathlib import Path

# Name when the face is not recognized
UNKNOWN = "Unknown"

# Distance threshold for face matching; lower is stricter.
MATCH_THRESHOLD = 0.6

# Path to serialized face encodings generated by training.py
ENCODINGS_PATH = Path(__file__).resolve().parent / "encodings.pickle"
